# Generated by Django 6.0.5 on 2026-05-20 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='estado',
            field=models.CharField(choices=[('Borrador', 'Borrador'), ('Emitida', 'Emitida'), ('Enviada', 'Enviada'), ('Pagada', 'Pagada')], default='Emitida', max_length=20),
        ),
    ]
