# Generated by Django 6.0.5 on 2026-05-20 03:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_ordencompra_estado_proveedor_email'),
        ('inventario', '0002_alertasistema'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertasistema',
            name='producto_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alertasistema',
            name='proveedor_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='proveedor_predeterminado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='compras.proveedor', verbose_name='Proveedor Predeterminado'),
        ),
    ]
