# Generated by Django 6.0.5 on 2026-05-20 05:32

import django.db.models.deletion
import inventario.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_ordencompra_estado_proveedor_email'),
        ('inventario', '0003_alertasistema_producto_id_alertasistema_proveedor_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='proveedor_predeterminado',
            field=models.ForeignKey(blank=True, default=inventario.models.get_default_provider, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='compras.proveedor', verbose_name='Proveedor Predeterminado'),
        ),
    ]
